### ISSUE TITLE
Result_format warning at exceptation/validator level, but I have it at Checkpoint Level

### ISSUE THREAD

**Issue by jmcorreia** [fivetran/great_expectations#7338]
**Describe the bug**
I am using Great Expectations 0.15.50 on Spark using RuntimeBatchRequest (in memory dataframe) and I am specifying result_format at checkpoint level as you can see below. However, in my local tests I am still getting a Warning saying that I am doing it at validator level "UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.".
I could not see these warning in my production executions in Spark/Databricks. It is only happening locally with pytest. Moreover,  the behavior is still the expected one, result_format is working as complete and unexpected_index_column_names is what I have defined.
Note: I noticed that you are ignoring these warning in your pytest https://github.com/great-expectations/great_expectations/blob/develop/pyproject.toml. Any reason for that? Should I do it as well? Or is there a better way to solve this?

**To Reproduce**
1 -
```
checkpoint_name = "checkpoint"
checkpoint_config = {
    "name": checkpoint_name,
    "class_name": CLASS_NAME,
    "config_version": DDATA_CHECKPOINTS_CONFIG_VERSION,
    "run_name_template": f"%Y%m%d-%H%M%S-{checkpoint_name}",
}
context.add_or_update_checkpoint(**checkpoint_config)

results = context.run_checkpoint(
    checkpoint_name=checkpoint_name,
    validations=[
        {
            "batch_request": batch_request,
            "expectation_suite_name": expectation_suite_name,
        }
    ],
    result_format={
        "result_format": "COMPLETE",
        "unexpected_index_column_names": source_pk,
    },
)
```

**Expected behavior**
No warnings.

**Environment (please complete the following information):**
 - Operating System: MacOS, pytest locally. Spark and Databricks for production.
 - Great Expectations Version: 0.15.50

**Additional context**
In addition to these, I also have many more warnings in the local tests, due to GX. Are there any plans to improve this? Few examples below. They are mostly coming from the Onboarding Data Assistant.
1. DeprecationWarning: `ipykernel.pylab.backend_inline` is deprecated, directly use `matplotlib_inline.backend_inline`
2. FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
3. FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
4. FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
5. WARNING  great_expectations.expectations.metrics.column_aggregate_metrics.column_histogram:column_histogram.py:296 Discarding histogram values below lowest bin.
6. WARNING  great_expectations.expectations.metrics.column_aggregate_metrics.column_histogram:column_histogram.py:302 Discarding histogram values above highest bin.

Thanks.

Let me know if you require anything else.

**Comment by alexsherstinsky** [comment]
Hello, @jmcorreia -- thank you very much for reporting this inconsistency and providing an example for how to reproduce it.  We will investigate on our end and get back to you with the plan for the resolution and/or any follow up questions.  Thanks again.

**Comment by jmcorreia** [comment]
Hi @alexsherstinsky. Do we have any news on this one?

**Comment by alexsherstinsky** [comment]
Hi @jmcorreia -- thank you very much for the reminder.  I am working on a related issue right now, and I will revisit this one thereafter.  I will keep you posted.  Sorry for the delay.  Thank you.

**Comment by alexsherstinsky** [comment]
Hi @jmcorreia Sorry for the delay.  We are still investigating.  Thank you for your patience.

**Comment by tyler-hoffman** [comment]
Hi @jmcorreia I'm working on reproducing this, but so far without success. Would you mind sharing a bit more info? What python version are you on? Can you share more of your code, just so I can get closer to your specific setup? And just to triple check, you're definitely on 0.15.50? The only reason I ask the latter is because the iteritems deprecation warning should have been fixed as of 0.15.29 (with this PR: https://github.com/great-expectations/great_expectations/pull/6205).

Thanks for any info you have! I'll keep poking at this to see what I can come up with.

**Comment by jmcorreia** [comment]
Hi @tyler-hoffman, thanks for the update. Did you have a look at all the ignores defined in the pyproject.toml? Even the iteritems seems to still be there.
![image](https://github.com/great-expectations/great_expectations/assets/11615737/32cd14b7-827a-46f6-bc7f-2c789e0c1d94)
I am using python 3.8. Even on great-expectations 0.16.5, which I am now using, I am still getting the warnings on the iteritems (and all the others about the result_format defined at wrong levels).
If I add all these, my warning severely reduce:
<img width="1131" alt="image" src="https://github.com/great-expectations/great_expectations/assets/11615737/36650dc0-efc0-4e99-9f97-c815c8b36c06">
In terms of code, all these are mostly coming from the onboarding data assistant I believe, but let me know if you need further details and I can try to get them meanwhile. 
`context.assistants.onboarding.run()`

**Comment by austiezr** [comment]
Hey @jmcorreia; thanks for providing this further detail. We've been unable to reproduce most of these warnings, though several of them appear to be linked directly to the type and structure of your data in particular. If you're able to resolve these, we would welcome a contribution here! Otherwise, I'll leave this issue open for the next week, and close out if we're still unable to reproduce. 🙇

**Comment by austiezr** [comment]
Closing out for now; feel free to re-open if picked up for contribution. 🙇

**Comment by jmcorreia** [comment]
Hi @austiezr ,
I found what the root cause is. Basically even if we define result_format only at Checkpoint level, GX is still considering the default configs/kwargs of the expectations (which include result_format = Basic) and default config for the validator (`basic_runtime_configuration`, which also includes result_format = Basic).
You can observe this in the method validate of expectation.py.
I think the warning would deserve to be enhanced, as it does not make sense for people to get this warning.
